name: Web.BuildQuality

on:
  push:
    paths: ./web
    branches: ["develop", "main"]
  pull_request:
    types: [opened, synchronize, reopened]
  workflow_dispatch:

permissions:
  pull-requests: read

jobs:
  build:
    name: Build and analyze
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./web

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 21.2.0

      - name: Install SonarScanner
        run: |
          npm install -g sonarqube-scanner

      - name: Install dependencies
        run: |
          npm ci
          npm run build

      - name: Unit tests
        run: |
          npm run cy:run-unit

      - name: E2E tests
        run: |
          npm run dev &
          npm run cy:run-e2e

      - name: Run SonarCloud analysis
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUBS_TOKEN }}
          SONAR_PROJECT_KEY: ${{ secrets.SONAR_PROJECT_KEY_WEB }}
          SONAR_ORGANIZATION: ${{ secrets.SONAR_ORGANIZATION }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
          SONAR_TOKEN: "${{ secrets.SONAR_TOKEN_WEB }}"
        run: |
          sonar-scanner \
            -Dsonar.projectKey=$SONAR_PROJECT_KEY \
            -Dsonar.organization=$SONAR_ORGANIZATION \
            -Dsonar.host.url=$SONAR_HOST_URL \
            -Dsonar.login=$SONAR_TOKEN \
            -Dsonar.coverage.exclusions="cypress/**/*.*, **/*.d.ts, **/*.cy.tsx, **/*.cy.ts, **/libs/**" \
            -Dsonar.exclusions="**/*.cy.*" \
            -Dsonar.javascript.lcov.reportPaths=coverage/lcov.info
